### ISSUE TITLE
Download bioconductor Wasm packages from R-Universe

### ISSUE THREAD

**Issue by georgestagg** [posit-dev/r-shinylive#125]
Currently, bioconductor packages are handled badly. It is possible to export them using the Shinylive R package, but only by installing the R-Universe version of the package locally. Instead, we should detect bioconductor packages and automatically pull them from the https://bioconductor.r-universe.dev/ repo.

**Comment by eingemaischt** [comment]
Another option would be to generally "fall back" to other repros if a package is not available in one of them.

**Comment by georgestagg** [comment]
Closed with #131.
