### ISSUE TITLE
data.table package crashing shinylive

### ISSUE THREAD

**Issue by Luke-Symes-Tsy** [posit-dev/r-shinylive#126]
For some reason loading the data.table package is now crashing shinylive for me - minimal example here: https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAEylKg1-rU4ASgA6EMAF8AukA

![image](https://github.com/user-attachments/assets/e202acab-51f6-4379-949a-3856611b58e1)

**Comment by georgestagg** [comment]
Does [this slightly less minimal example](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IdJiw4ATKKSgZZ9anGEQRAV1oACADwBaTeQAepAPJrSqc+yFheNlZziMAbk536AZmogFStEux8lqS4mkTmwQKaICKaYRHmACS87pqMFJJOACpwxtZgABJw1NRE9iIAviIiPHysAILo7BqaALyaGqGOLm7t3a6MKmAVALpAA) work for you?

The webR package repo was recenty updated, can you try clearing your cache? In Chrome this can be done quickly: with dev tools open right click the refresh button and click "Empty cache and hard reload". Does that help?

**Comment by Luke-Symes-Tsy** [comment]
Many thanks, things are now working again.
