### ISSUE TITLE
Usage of global.R

### ISSUE THREAD

**Issue by stla** [posit-dev/r-shinylive#18]
Hello,

ShinyLive is very cool, thank you for the work.

I made an app `app.R`  accompanied with a `global.R` file but `global.R` is not executed. I tried to put it at first position in the JSON file but that does not solve the problem. If it is not possible to use `global.R`, it would be nice to add this feature. If it is possible, how?

**Comment by schloerke** [comment]
@stla I have tried to recreate an app with a global.R and an app.R and I could not get global.R to be automatically called with an `app.R` file with regular shiny.

## Reprex:

#### `./app.R`

```r
library(shiny)

shinyApp(
    fluidPage(
        sliderInput("n", "Global value: N", 0, 100, global_value),
        verbatimTextOutput("txt", placeholder = TRUE),
    ),
    function(input, output) {
        output$txt <- renderText({
            paste0("The value of n*2 is ", 2 * input$n)
        })
    }
)
```

#### `./global.R`

```r
global_value <- 50
```

**Comment by schloerke** [comment]
However, when using ui.R and server.R, `global.R` is sourced.

[These lines](https://github.com/posit-dev/r-shinylive/blob/c767d1a8dbdcfad2525366938c1f2f20ff0d2b54/R/export.R#L38-L40) will need to be changed to:

```r
  if (!(
    fs::file_exists(fs::path(appdir, "app.R")) ||
      fs::file_exists(fs::path(appdir, "server.R"))
  )) {
    stop("Directory ", appdir, " does not contain an app.R or server.R file.")
  }
```

**Comment by stla** [comment]
Wow, I prefer the `ui.R + server.R` way, I didn't know it was possible with ShinyLive! Thanks!
