### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Krishnakumarshrestha** [posit-dev/r-shinylive#26]
Error starting app!
Robj construction for this JS object is not yet supported

**Comment by schloerke** [comment]
Please provide a [reprex](https://reprex.tidyverse.org/) so that we may help you with this error.

**Comment by Krishnakumarshrestha** [comment]
library(shiny)
library(dplyr)
round_term <- function(term) {
  if (abs(term - floor(term)) < 0.5 & abs(term - floor(term)) !=0) {
    return (round(term) + 0.5)
  } else if (abs(term-floor(term)) > 0.5 & abs(term - floor(term)) <1){
    return(ceiling(term))
  }else {
    return (round(term,1))
  }
}


ui <- fluidPage(
  titlePanel("Premium Rate Calculator"),
  includeCSS("style.css"),
  sidebarLayout(
    sidebarPanel(
      numericInput("age_input", "Enter your age:", value = 18, min = 18, max = 64),
      numericInput("term_input", "Enter the term (in years):", value = 1, min = 1,max=6.5),
      actionButton("calculate_button", "Calculate Premium Rate")
    ),
    mainPanel(
      textOutput("premium_output")
    )
  )
)

server <- function(input, output) {
  premium_rate <- function(age, term1) {
    # Load the premium data
    load("premium_data.RData")
    
    # Define age range based on the age input
    age_range1 <- ifelse(age >= 18 & age <= 35, "18 to 35",
                         ifelse(age >= 36 & age <= 50, "36 to 50", "51 to 64"))
    
    # Filter premium data based on age range and term
    selected_rate <- premium_rate %>%
      filter(age_range == age_range1, term == term1) %>%
      pull(rate)
    
    return(selected_rate)
  }
  
  # Use observeEvent to calculate premium when the button is clicked
  observeEvent(input$calculate_button, {
    age <- input$age_input
    term <- input$term_input
    term <- round_term(term)
    # Call your premium_rate function to get the premium rate
    rate <- premium_rate(age, term)
    
    # Display the premium rate
    output$premium_output <- renderText({
      paste("Premium Rate:", rate)
    })
  })
}

shinyApp(ui, server)

**Comment by schloerke** [comment]
@Krishnakumarshrestha May I also have your style.css and premium_data.Rdata files? Thank you!

**Comment by Krishnakumarshrestha** [comment]
library(shiny)
library(dplyr)
term <- c(1.0, 1.0, 1.0, 1.5, 1.5, 1.5, 2.0, 2.0, 2.0, 2.5, 2.5, 2.5, 3.0, 3.0, 3.0, 3.5, 3.5, 3.5, 4.0, 4.0, 4.0, 4.5, 4.5, 4.5, 5.0, 5.0, 5.0, 5.5, 5.5, 5.5, 6.0, 6.0, 6.0, 6.5, 6.5, 6.5)
age_range <- c("18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64", "18 to 35", "36 to 50", "51 to 64")
rate <- c(1886, 2575, 5476, 2629, 3663, 8014, 3046, 4025, 7650, 3708, 4931, 9463, 3924, 5330, 9970, 4511, 6152, 11565, 4823, 6490, 12435, 5376, 7251, 13939, 5548, 7505, 14900, 6063, 8216, 16350, 6128, 8811, 17220, 6605, 9512, 18622)

# Create the data frame
premium<- data.frame(term, age_range, rate)


round_term <- function(term) {
  if (abs(term - floor(term)) < 0.5 & abs(term - floor(term)) !=0) {
    return (round(term) + 0.5)
  } else if (abs(term-floor(term)) > 0.5 & abs(term - floor(term)) <1){
    return(ceiling(term))
  }else {
    return (round(term,1))
  }
}


ui <- fluidPage(
  titlePanel("Premium Rate Calculator"),
  includeCSS("style.css"),
  sidebarLayout(
    sidebarPanel(
      numericInput("age_input", "Enter your age:", value = 18, min = 18, max = 64),
      numericInput("term_input", "Enter the term (in years):", value = 1, min = 1,max=6.5),
      actionButton("calculate_button", "Calculate Premium Rate")
    ),
    mainPanel(
      textOutput("premium_output")
    )
  )
)

server <- function(input, output) {
  premium_rate <- function(age, term1) {
   
    
    # Define age range based on the age input
    age_range1 <- ifelse(age >= 18 & age <= 35, "18 to 35",
                         ifelse(age >= 36 & age <= 50, "36 to 50", "51 to 64"))
    
    # Filter premium data based on age range and term
    selected_rate <- premium %>%
      filter(age_range == age_range1, term == term1) %>%
      pull(rate)
    
    return(selected_rate)
  }
  
  # Use observeEvent to calculate premium when the button is clicked
  observeEvent(input$calculate_button, {
    age <- input$age_input
    term <- input$term_input
    term <- round_term(term)
    # Call your premium_rate function to get the premium rate
    rate <- premium_rate(age, term)
    
    # Display the premium rate
    output$premium_output <- renderText({
      paste("Premium Rate:", rate)
    })
  })
}

shinyApp(ui, server)



and css 


/* styles.css */

/* Style the premium rate box */
#premium_output {
  border: 1px solid #000; /* Border with 1px width and black color */
  padding: 10px; /* Add some padding inside the box */
  display: inline-block; /* Make the box inline so it wraps around the content */
  border-radius: 5px; /* Add rounded corners */
}
