### ISSUE TITLE
Error 404 when using library(plumber) pr() %>%     pr_static("/", "site/") %>%     pr_run()

### ISSUE THREAD

**Issue by DJ-Jam1** [posit-dev/r-shinylive#33]
Trying to get started with using R and was following the guide on https://posit-dev.github.io/r-shinylive/#installation/ 

Export of myApp appears successful in the site folder. I then ran the following command: 
`library(plumber)
pr() %>%
    pr_static("/", "site/") %>%
    pr_run()` 

The preview returns an Error 404 and fails to find the document. 
for context also ran this on the development brand and also released and on 2 different machines. 

Any help is greatly appreciated

**Comment by schloerke** [comment]
Was able to reprex within the RStudio IDE.  Got caught by the IDE wanting to open up the `/__docs__/` route of root. 

In #40 , I changed the instructions from the plumber steps above to `httpuv::runStaticServer(EXPORT_DIR)` (e.g. `httpuv::runStaticServer("site/")`). 

I've tested the new commands in the IDE and the browser opened up as expected.

---------------------

Closing

**Comment by brownj31** [comment]
@schloerke I installed the latest versions of `shinylive` and `httpuv` from the GitHub repository, and I still get a `404 Not Found` error on the local server.  The code I used is below.  Are there any additional instructions?

```
shinylive::export('webr_example', 'example_app')
httpuv::runStaticServer("example_app/")
```
