### ISSUE TITLE
shinylive in netlify

### ISSUE THREAD

**Issue by joscani** [posit-dev/r-shinylive#34]
Hi. I'm a newbie in shinylive, I try to follow the example in https://posit-dev.github.io/r-shinylive/  after 

```r
shinylive::export("myapp", "site")
```

I push the site directory into my netlify site https://muestrear-no-es-pecado.netlify.app/ under the folder 
https://muestrear-no-es-pecado.netlify.app/shiny_site/  but I don't get anything. 
Any idea? .  Thanks
Note: It works if I render my quarto website in local. but not in netlifty

**Comment by schloerke** [comment]
Any console warnings in your browser?  Or any Network tab failures in your developer window for the web page?

I wonder if it'll be related to cross-origin isolation from the host: https://github.com/posit-dev/shinylive/blob/c6fa4dd0c1ad17a6848d5e0a571ea7fccbdf9212/src/shinylive-sw.ts#L19C1-L25

**Comment by joscani** [comment]
ups. 
I think the problem was my .gitignore file . Right now is works
