### ISSUE TITLE
Error loading packages

### ISSUE THREAD

**Issue by clementrx** [posit-dev/r-shinylive#37]
Hi ! 

For context, I'm using **shinylive** with github to deploy my .html.

For some packages (highcharter, plotly) when I'm using them the page doesn't load.
Moreover, when I'm trying on [Shiny Editor](https://shiny.posit.co/), I have the message : 

`Downloading webR package: plotly`
`Error: could not find function "plotlyOutput"`
`Error: attempt to apply non-function`

Is there a specific procedure for using certain packages? And if so is it possible to add it to the documentation with an example?

Thanks

**Comment by schloerke** [comment]
Can you paste your app code below so that I may hopefully reprex the behavior on my side?

**Comment by schloerke** [comment]
Thank you for the app code!

---------------------------------

Ah. So your app is getting caught by shinylive/webr's capabilities.

List of packages that webr (which posit-dev/r-shinylive uses to load packages) supports: https://repo.r-wasm.org/
Screenshot:
![Screenshot 2023-12-01 at 4 32 07 PM](https://github.com/posit-dev/r-shinylive/assets/93231/3fdb1012-5982-458b-85bd-fa63aa6eaa54)

`{igraph}` is one of the packages (like `{curl}` or `{XML}`) that is having trouble compiling for WebAssembly.

We do not have a known timeline (if at all) of when these missing packages will become available.

---------------------------------

Closing
