### ISSUE TITLE
Tinker editor console loads with error: there is no package called ‘httpuv’

### ISSUE THREAD

**Issue by coatless** [posit-dev/r-shinylive#44]
Visit any example here:

https://shinylive.io/r/examples/#hello-shiny

Receive:

![shinylive-r-editor-error](https://github.com/posit-dev/r-shinylive/assets/833642/4b1d2400-ae93-4745-9a84-48892803a733)

Maybe related to the new shinylive version?

**Comment by georgestagg** [comment]
Hi,

Does reloading with an empty browser cache help? In Chrome you can do this easily by right-clicking the refresh button near the address bar.

If it still fails after clearing the cache, could you load up the network tab and JavaScript console in the browser dev tools and let us know if there are any error messages or network connection failures in the logs as the page loads?

**Comment by coatless** [comment]
Unfortunately, no. I tried both the local setting and completely deleting all data. 

Local page reset:

![shinylive-reset-website-data-url-bar](https://github.com/posit-dev/r-shinylive/assets/833642/f097523c-4d66-48a3-9e70-7635ab9c1125)

Browser hard reset:

![shinylive-hard-browser-reset](https://github.com/posit-dev/r-shinylive/assets/833642/84f7aa3e-d75d-423e-a63b-e568592b1b74)

Error message in JS console: 

<img width="1251" alt="Screenshot 2023-12-19 at 10 40 35 AM" src="https://github.com/posit-dev/r-shinylive/assets/833642/eb18a113-d1c3-4bbd-a5a2-9c933e16d922">

Error Text:

```
shinylive.js:64 Uncaught (in promise) Error: Unexpected response type: "null", expected "list".
    at y4 (shinylive.js:64:97)
    at async B2 (shinylive.js:43:4848)
    at async r1.makeRequest (shinylive.js:377:781)
```

**Comment by georgestagg** [comment]
Thanks, sorry to ask but could you run a couple more tests?

Do things work better in Incognito/Private Browsing mode? Or in other browsers? I have a hunch this is related to the Service Worker, but I'm not 100% sure yet.

If it works in incognito mode, please can you please visit `chrome://serviceworker-internals/` in a new tab (not incognito), then search for "Scope: https://shinylive.io/r/`. For any matching entries, please click the "Stop" button, then "Unregister". Finally, perform another hard reload of the page (not incognito).

Sorry to have to ask, but doing this will definitely rule out any caching/SW issues.

**Comment by coatless** [comment]
@georgestagg If I switch over to Safari, I can get it to render. However, I have to do a _hard_ refresh.

![shinylive-safari-with-reset-mid-load](https://github.com/posit-dev/r-shinylive/assets/833642/daa6ce7a-eeef-4c81-9c74-ad54282cb29a)

With Firefox, everything works as normal:

![shinylive-firefox-first-run](https://github.com/posit-dev/r-shinylive/assets/833642/ac29e5c6-535e-481b-b602-64aa2938ebfa)


Putting Chrome into Incognito didn't change anything:

![shinylive-demo-from-private-browser](https://github.com/posit-dev/r-shinylive/assets/833642/7a996597-a0e8-4a14-855d-c92921d2a9bd)

**Comment by georgestagg** [comment]
I've invalidated the AWS cache for R packages hosted at `repo.r-wasm.org`. I might need to automate that step in the future.

@coatless, please can you try refreshing the page again to see if it has helped? You may need to perform two hard refreshes so that both the network and Service Worker cache obtain an updated version of the files.

**Comment by jeroen** [comment]
For me the problem was solved after manually purging the history+cache in the browser. Simply forcing a refresh of the page did not seem to fully wipe the cache.

**Comment by coatless** [comment]
Works great now with the cache invalidated over at AWS in Chrome! Also, the need to do a hard refresh in safari also disappear. Thanks 👍
