### ISSUE TITLE
MathJax Equations Render Successfully in UI, but Encounter Issues Within Output

### ISSUE THREAD

**Issue by ydkristanto** [posit-dev/r-shinylive#49]
I've observed a peculiar behavior with MathJax equations in my Shiny app. When I directly include the equations in the UI using the following code:

```r
tags$head(
  tags$script(
    src = "https://polyfill.io/v3/polyfill.min.js?features=es6",
    async = TRUE
  ),
  tags$script(
    src = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js",
    async = TRUE,
    id = "MathJax-script"
  )
)
``` 

they render successfully. However, when attempting to display the same equations within an output element, such as using `renderText` or `renderUI`, issues arise.

I appreciate any insights or guidance in resolving this behavior. Thank you for your assistance.

**Comment by gadenbuie** [comment]
Hi @ydkristanto! Can you please include [a small, complete app that reproduces your issue](https://community.rstudio.com/t/shiny-debugging-and-reprex-guide/10001)? Having a full example to run will greatly increase the chances that we'll be able to help you.

**Comment by georgestagg** [comment]
It looks like the default MathJax URL used by Shiny (`https://mathjax.rstudio.com/latest/MathJax.js`) is not being served with the HTTP header `Cross-Origin-Resource-Policy: cross-origin`. As such, I think the browser is blocking it from being loaded in the embedded `iframe` that shows the resulting Shinylive app on the page.

Switching to a URL that serves MathJax with that header should avoid the problem, for example by modifying the start of your app to read:

```r
library(shiny)
options(shiny.mathjax.url = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js")
```

Example app: [https://shinylive.io/r/editor/#code=Nob...AA](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IRVKVolOXXvwwwopbgCsoADwwBXRtQAEAXl1Cw3UqVSdEAeisEAJhGWcMBakU12AZtRZwXRGCsoVTUrOnpOKwUlEKsAJgwAdiSrAFlFbgApdQwnY2EIEU1aXQAeAFpdb2K7AAUoAHM4dhFdXQlSajgDXQBydKVstV0AUTVYVC7OXtxW3QB3WiUBrPV2AVmINu44alQAFTg1UnZegEEt2kZmCRIoPQhNGHo4RiMhD5aPoU4AR0ZSCA4gBfb5CAptSFQtpQCB2XRQKrMAi3LYAEjRAEZymDPMiQJjgUDgRjehs5js9odjqdYfDEZ4oCiEfR3KR3p8wahaGCBIg5tCoRjcci4lySoYRUyQGC-gCQXEOUJ7ERSALBW0pQQZd85YC4gBqWX-Ugg4GKsEqtVbDWQrU6j56oFG3Um53G+XAr0W75Wzik8k24oAeU05jDpyOmLJmzaIbDqAjvSOcRjc3j4ZOybUAGY00HaKHM5G1AAWfNtAg7AgAa1ZagAkhBE1mjgBWAD6ADdaJwGF0Zn0AMrcIjzUbjGCTbptwcAMTOABkhyNA3HCwmk+2ySICiJOK8u68ypVPJoICjJBB2HwW7hdGy77oD5w+yQBLoZTbH2G0VGT7ojAUHYrwAKoNuwX5QosywZEM7CUgcRxZgAIqw0AwLQBAPpu7KYogbTCt89yoNwUAAHpxAGEK6MCNE-qQf5qIqFSAcBYEQVBkIwdwKzweq2y7EhNK9HSOGZroioYjmlEGqWlH6G2lEBrG0KIdSWZiQxug5roRGOnwlFfB8ShwKQUACC6HzEJwRlgqZ5kCPomIBuqNF0XMDFMbprFAXCHGQeqPF8WsAm6OpyGnPsOy6PQmicKwugAMJQJoVaJXYvakIwDBhleYW2npaL2oSDpCNyYINLAChgrM3xdJ4pDAJiuhGjahVQmCDUnPaajlGoHYAAxEpV1VQKC3w5Q0pgCJRYJTaYAC6E0fAAhNRcwed+uFMaWAF+SBjDgYF7W6MMvnuHC7CMAQqXpewmIbDpNFtMFcFrJwqA5WQngtGADaeEq7AABq8rovYIsld3cIlzBwgEuhdiwtBQPQXT3qZhSnR1HUYrUINKl0vy6AApBgg05oDH6GGTFOeMKeBnfeqC3WlMPsGoAhc5t9E7e2+3sUdnHqrQgPsKtt6-u23a9v2cAfkBpDaNeL0LEsvHvWoLTY+FQkaacACa7i6HYRC6KI7IHt08DgxASwo9Q1CsARGJwORIAlOKwKtbomKYnEOb+4HAc9INrmne5BSgljPB8KwZzoOwxT3gejBHowAhgMCi1AA)
