### ISSUE TITLE
sourcing the shiny app

### ISSUE THREAD

**Issue by topepo** [posit-dev/r-shinylive#53]
It looks like using the quarto `file` options doesn't work. 

[Here's an example repo](https://github.com/topepo/center-shiny-figure/blob/main/index.qmd#L122-L134) with the app inside of the qmd and then another using `file: <filepath>`. Let me know if I'm doing something wrong.

**Comment by gadenbuie** [comment]
You aren't doing anything wrong, the shinylive extension doesn't support reading from external files (yet!). It would certainly be a useful feature! I think https://github.com/quarto-ext/shinylive/issues/37 is a request for this feature, which would need to be implemented in that repo (for the quarto extension).
