### ISSUE TITLE
Latest version of `{bslib}` with `{shinylive}` crashes due to trying to re-create the `/tmp` directory

### ISSUE THREAD

**Issue by coatless** [posit-dev/r-shinylive#56]
There seems to be an issue with the latest version of `{bslib}` package. Calling the `page_sidebar()` layout option is causing the shiny app to crash due to an attempt to re-create the `/tmp` directory

MWE: [Shiny demo app](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IdJiw71OY4RBEBiAAQAROADM+cRQFUAkorVFGitKkWluUUooAmzAO6cTi3p1JEA5sxiKAtP98RAFdaRQAeX0VUKA84AH1OWhs4ehZ2EUVFDMUlAEF0c1pSai0AwIhM0iKSgAUoCDhqdLAACUbqIkUAZV5+AEIhMAFcbOylLqSUlkVqKFYiIOt7Iu5FPlRFkwgbRQXSDetkjQgi2hInMuzE5NTjAF5Fa6nGdiJUCkUHwbeKQZGKzKAoHA4HSSaMXQQA7sdaLXQ7L5geh8Th-bIgjGYrGzeiNT5ZMAAOSCMFxxiIakUyIgnEQaIBWMZTJgfHxAEZ-kyuViYFAAB74gCsAAZOdzxUCAG5QahBLQPADMwuG2RVALGigA8osDohFC1aG5PN4-AFsqgOqRtftFq8dXCEQSbIbSDVLYNZLIFCp1JpHnBGJKAzNPLQCIpGHAAI4hSM7dy2BzOVzuLywU3+EScANB4wRAxBCAEKokGFQxa4Xb20gCRQgUYApQGo1pnwU8zcLSa6g7ABiUBWaiC1EUAHE4Kxs8ZlFYoBnypklMsLBHo3K3HAdhASWTdpTqajG4oACquRRwPmoSOcRIkDtWRSxBrMchOOcp43pw2KezMdCbtYKjnAgZWoDUE0jbYAzdIhrATPhnRA8h71IOlGw1NkMEUXRrG-QZIygYtaCDQYtnjTtI0MSNHm4BYeypLQoEWIheSqEDqGoVgNUBSNfAvOACEWAD7E7CpYVIJwywOAASA9awISwIFiDUACYsJwpw9gOcxWHeNY3yid0AS0xZpOdNwYOsfNIOSRhLPYesGSyJyBUBfM1AHCwh2oaT7E8vgPHRKkUXCSJsyjdgWQgdg+WGRReT5GK4pKJSLAwPZ8XE2SQoAakUNlZCBIKUxiysmDgKAAGsnAeA9K2IEdEXkAB2QVclyZQACE-ipIxbPxQYRKKOB6SxPkcQGsAAHV-KUwp4HMToGj5awAyCVASwqMt4pRYQ8CC4FeVZRFm1TE12z8045qqeBUSGILsgAX0K5zHpEb0AGECOQno+FYEwCkuGlelYfJUHYEJ8RCSsp1zfFYYDWQwEegBdIA)

![shinylive-r-crash-on-bslib-element](https://github.com/posit-dev/r-shinylive/assets/833642/78fa8502-74ce-4796-956d-90c7a10bdd3a)

<details>
<summary> stacktrace with error text - [EEXIST] Failed to make directory '/tmp': file already exists </summary>

```r
Attaching package: ‘bslib’

The following object is masked from ‘package:utils’:

    page

Warning: Error in : [EEXIST] Failed to make directory '/tmp': file already exists
  61: <Anonymous>
  60: <Anonymous>
  59: fs::dir_create
  58: <Anonymous>
  57: mapply
  56: write_file_attachments
  55: bslib::bs_theme_dependencies
  54: x
  53: as.tags.shiny.tag.function
  46: func
  45: FUN
  44: lapply
  43: FUN
  42: lapply
  41: FUN
  40: lapply
  39: FUN
  38: lapply
  37: rewriteTags
  36: tagify
  35: renderTags
  34: renderDocument
  33: renderPage
  32: appObj()$httpHandler
  31: handler
  30: handler
  29: handler
  28: handlers$invoke
  12: handler
  11: app$call
   8: eval [<text>#4]
   7: eval
   6: efun
   1: <Anonymous>
```
</details>

**Comment by scrapeable** [comment]
This bug has been throwing me for a loop the past couple days, thanks for figuring out the source @coatless ! I'm using `bslib::page` and getting the same error.

**Comment by gadenbuie** [comment]
Thanks for reporting @coatless! @scrapeable Do you remember when you first noticed the issue?

**Comment by scrapeable** [comment]
@gadenbuie I believe it started happening 6 days ago, my shinylive app which had previously been working stopped working Monday.

**Comment by georgestagg** [comment]
My apologies, an update to webR's binary R package repo caused this. I've just now rebuilt the R packages required for running Shinylive for R and have invalidated the AWS cache.

Things should now work again after clearing your browser cache and refreshing the page, but please let me know if you still encounter issues.

In the future, Shinylive for R will use pinned Wasm binary package assets rather than the general webR package repo, which should avoid these kinds of issues.

**Comment by scrapeable** [comment]
@georgestagg Thank you! Everything on my end is back to normal.
