### ISSUE TITLE
Mathjax not rendering

### ISSUE THREAD

**Issue by EinMaulwurf** [posit-dev/r-shinylive#57]
*Problem:* Mathjax is not rendering when inside a `shinylive-r` app.

*Minimum Reproducible Example*:
```
ui <- fluidPage(
  titlePanel("Example"),
  withMathJax(),
  helpText('An irrational number \\(\\sqrt{2}\\)')
)

server <- function(input, output) {}

shinyApp(ui = ui, server = server)
```

running as a "normal" shiny app works fine, but when it's inside a `shinylive-r` environment it does not render properly.

<img width="517" alt="Bildschirmfoto 2024-02-22 um 18 40 32" src="https://github.com/posit-dev/r-shinylive/assets/116873121/8f650ca5-0935-4925-9a0e-920f88b771de">

**Comment by georgestagg** [comment]
This is a duplicate of #49, and the same underlying problem as #51.

Should be fixed by https://github.com/posit-dev/shinylive/pull/112.

**Comment by EinMaulwurf** [comment]
Thanks.

I fixed it by including
```r
library(shiny)
options(shiny.mathjax.url = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js")
```
