### ISSUE TITLE
Distribute Wasm package binaries as part of shinylive exported site

### ISSUE THREAD

**Issue by georgestagg** [posit-dev/r-shinylive#63]
@schloerke: Here is THE PLAN:

1) Run `renv::dependencies()` on shiny app to list dependencies at build time

2) Loop through the list of packages, use `packageDescription()` to find information.

3) Lookup information about package list:
 - If "Repository" is CRAN, talk to  <repo.r-wasm.org> (& eventually p3m) using base R repo functions.

 - Otherwise, use "Repository" URL (e.g. https://r-lib.r-universe.dev)
    * Talk to remote repo using base R repo functions.
    * Build and try the "well-known" `.../emscripten/...` path to look for a wasm binary (e.g. HTTP `HEAD` request).
    * If not found, `stop()`.

 - If "RemoteType" is `github`, look for a Wasm release using GitHub API.
   * If the GithubRef/RemoteRef is not a tag, `stop()`
   * If it is a tag, try to download a wasm binary attached to release.
   * If no wasm binary on the release, `stop()`. Print a message asking the user to use r-wasm/actions.

4) Build package library for inclusion as part of exported static files
 - Create: `.../exported/webr/packages/[PACKAGE_NAME]/`
    
 - Generate metadata (e.g. GitHub asset ID)

 - If metadata matches existing metadata in `export.json`, don't bother re-downloading.

 - Download and copy to e.g.
        `exported_app/webr/packages/ggplot2/library.data`
        `exported_app/webr/packages/ggplot2/library.metadata`

 - Save metadata:
        `exported_app/webr/packages/ggplot2/export.json`

5) (At runtime, using Shinylive & JavaScript):
    - `library(shiny)` packages are handled by Shinylive. //TODO: https://github.com/posit-dev/shinylive/pull/82/files - Blocked by AWS
    - Run `renv` at runtime to get the package list.
    - Loop over the package list, run `webr::mount("/lib/[PACKAGENAME]", "./exported_app/webr/packages/[PACKAGENAME]/library.data")`
    - Add `/lib/[PACKAGENAME]` to `.libPaths()`.
     - See https://github.com/posit-dev/shinylive/blob/3b30f2cf86e78f6d86aa69b5fc6b5ec5975de652/src/hooks/useWebR.tsx#L260

@schloerke to handle 1-4, @georgestagg to handle upgrade of webR in Shinylive to v0.3.0 and then 5).

**Comment by schloerke** [comment]
Will need deps of deps via `{pak}`

**Comment by gadenbuie** [comment]
This issue should be closed when we update the default shinylive assets version, correct?

* #93
