### ISSUE TITLE
Weird infinite loop error

### ISSUE THREAD

**Issue by seanbirchall** [posit-dev/r-shinylive#67]
I'm not sure what's happening here, something similar happened a month ago when the webR build was changed (Just tried finding the issue to reference here but cannot find it). Where I had an app that worked one day but stopped working the next. Very different error message this time around. 

![webr](https://github.com/posit-dev/r-shinylive/assets/156547477/958c035f-6fa5-4722-b097-4a05d5f57ca7)

This error loop runs for awhile then stops and returns `Cannot GET /webR/app_xxxxxx`

Even using the boilerplate old faithful app it still gives the same error when I export and run the app on a static web server. I'm using `Copying base Shinylive files from C:/Users/seanb/AppData/Local/shinylive/shinylive/Cache/shinylive-0.2.3/ to webR/` so maybe I just need to update my packages as it sounds like  a new webR release is coming soon.

**Comment by gadenbuie** [comment]
Hi @seanbirchall, thanks for the report. We're working to fix a small issue with the package repository used by shinylive. It should be back in working order in an hour or so.

**Comment by gadenbuie** [comment]
@seanbirchall this should be all cleared up now. You may need to clear your browser cache for shinylive.io to get the fix. (In Chrome, while viewing a [shinylive example](https://shinylive.io/r) under **View**, click **Clear cache and refresh**.)

**Comment by seanbirchall** [comment]
@gadenbuie everything looks good on my end again, thanks for the quick response!
