### ISSUE TITLE
Cannot read properties of null (reading 'deps')

### ISSUE THREAD

**Issue by ydkristanto** [posit-dev/r-shinylive#75]
Hello! I'm encountering an issue while attempting to use the Shinylive app to demonstrate network visualization using {network}, {GGally}, and {plotly} packages. When running the app on localhost, I'm receiving the following error message:

> Shiny Client Errors
> Error on client while running Shiny app
> Cannot read properties of null (reading 'deps')

Here I provided a reprex of the Shiny app code that I'm using:

```
library(shiny)
library(plotly)
library(network)
library(GGally)

# Data ----
edge_list <- data.frame(from = c(1, 2, 2, 4), to = c(2, 3, 4, 1))
node_list <- data.frame(
    id = 1:4,
    label = letters[1:4]
)

# UI ----
ui <- fluidPage(
    titlePanel("Reprex: Network Analysis"),
    sidebarLayout(
        sidebarPanel(
            selectInput(
                "nodes",
                "Nodes:",
                c(letters[1:4]),
                selected = letters[2:4],
                multiple = TRUE,
                selectize = TRUE
            )
        ),
        mainPanel(
           plotlyOutput("plot")
        )
    )
)

# Server ----
server <- function(input, output) {
    output$plot <- renderPlotly({
        # Filter
        node_filter <- node_list |>
            filter(label %in% input$nodes)
        # Apply filter
        edge_list <- edge_list |>
            filter(
                from %in% node_filter$id,
                to %in% node_filter$id
            )
        # Create network object
        net <- network::network(
            edge_list,
            vertex.attr = node_filter,
            matrix.type = "edgelist",
            ignore.eval = FALSE
        )
        # Plot the network
        plot <- ggnet2(
            net = net,
            node.color = "black",
            edge.color = "grey"
        )
        # Make it interactive
        ggplotly(plot)
    })
}

# Run the app ----
shinyApp(ui = ui, server = server)
```

I've run the app in RStudio, and it works fine. I've also checked all the packages; they are already in the [Wasm repo](https://repo.r-wasm.org/), as are their dependencies. Any assistance in resolving this issue would be greatly appreciated. Thank you!

**Comment by georgestagg** [comment]
I tried running you app at https://shinylive.io/r/ and saw the following message in the console:

```
Warning: Error in require_namespaces: please install the package 'sna'.  install.packages('sna') 
```

Does adding `library(sna)` to your `app.R` make the app behave as expected. Here is an [example on at shinylive.io with the extra line added](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IdJiw6pqRUtUEixzNuwhxSAdyKMA1sNEMlHAOJGo1OXsUSu0PSIDEAAgAiUUlEcBab55FwAJgDmcAD6dJykjgA8no7+blAYAGbM8OwpRDCOALyOBOwAjLiOAEzFZY4ALALFpEQ5eewVAMzFlcUFAnoQRP6h4ZExcQnJqXDsIo5TjrT+DQWI7ZPT1FD0cNQN1GrkjJzAC5UAuiJ2EE4AqgCSXj4iAK600bFJ1I-+AApQwRMQ046kWiyOBfVTUCZgLBwVCMOAAD0QjgAcmpNDpHABBaByTi0ThCMA1ZZTXF9egsAAyUFYRHupF+-3+pLg5MYoI2DMZXM4GzgBFIVwgqDpnK5YscBJ6fXxeGJ4sZBKRvTgnEQBNwcvl03y21Iu32hyORL+WsZPO2-ICWx2cD2wBKiyOGpNpumMHu1EBUjgDQAKlgLgBRZ2upm8-m0ABePty-qDmrFenFxvFMCgfHZ4ITjKkMjkAHk6cL6QTc6QCUnE3K9GcnABlW0AN1tt28Ih5jGbjGejiS9wgEZI7D4xeKtNIxYEjhAcvHxYAJGWe7CIH02dJZBwZy7GU4AGK0T227OOKWhJKH3Y9s9hPGRAA+AD4T-8L0fGOxVutNgBSPg-mYhTpecz04SsuScDF0DkXtL2PHd-gCYJbwiHskP6O9HCfF9pjfXZRVDDIsj-CAAJvPDbXnWYQ1DKY6kcEiyOVEIKMYKj-BwqZwN3RwAGFYTcH1VA0LRtEcIh6AAKz5csEOmYTr1RUTEEQYS0W0AjxXQlDSBorUu3IOEMDcUhu1yci4MYPT5TTUzaCM0hWFQGMJTAdCBnVTiZkCHpYQwOBGzMBo9wxCk60DE9uP+JwPg3AFuCEpSdBPJchkCHy1BKTSxQU8y1Gs8UzwwYhpDM1z6FWAhtE8uSuXQ4qiFKhoCUCWFWAJSKTycABZKBtB9IFAN2KAI2bE90rLOR2DLbiAF89FmkQHEcLB+3in00FQVtfAgHg+FYKDUHYR4GkeYoOy7BoLttAQwFmo4gA).

**Comment by ydkristanto** [comment]
Thanks, @georgestagg, for your assistance. The app works when I add `library(sna)`!
