### ISSUE TITLE
URL for running static server needs to escape characters on Windows

### ISSUE THREAD

**Issue by daattali** [posit-dev/r-shinylive#82]
On a Windows machine, after running `shinylive::export()` the last bit of the message is:

```
Run the following in an R session to serve the app:
  httpuv::runStaticServer("C:\Users\Dean\AppData\Local\Temp\RtmpaW6ZAM\shinylive-export14a1058a2616d")
```

If I copy-paste that to my R console, it fails. The slashes need to be escaped.

**Comment by jonthegeek** [comment]
Or just use `/`. Many hands are wrung about evil Windows slashes but Windows hasn't cared about backslashes in a decade or two.
