### ISSUE TITLE
Documentation clarification: {renv} is not required to be used by the shiny developer

### ISSUE THREAD

**Issue by daattali** [posit-dev/r-shinylive#84]
In the README, the section after "Usage" is "R package availability". It says that {shinylive} will inspect which packages are used via {renv}, and what to do if {renv} cannot find a package.

Perhaps this is a non-issue for others, but I interpreted it to mean that {shinylive} *expects* my shiny app to be using {renv}. I was surprised when an `export()` worked without me explicitly using {renv}, and only after reading the README a few times I understood that 
{shinylive} is **automatically** using {rnev} **internally**.

If you think the issue is me having to improve my reading comprehension then you can close this issue!

**Comment by gadenbuie** [comment]
The quote is:

> The [shinylive](https://posit-dev.github.io/r-shinylive/) web assets will statically inspect which packages are being used via [renv](https://rstudio.github.io/renv/).

I can see how the confusion would arise. I think we could either include a sentence noting that your project does not need to have an `renv.lock` and that we're using `renv` only for package discovery.

On the other hand, I think that sentence and the entire section would be even less confusing if we didn't mention renv at all and just said that "shinylive will automatically discover which packages are used in your application".

**Comment by daattali** [comment]
I agree with removing the mention of renv entirely.
