### ISSUE TITLE
readR::read_csv CURL dependency?

### ISSUE THREAD

**Issue by quincountychsmn** [posit-dev/r-shinylive#89]
It appears that even if read_csv is declared like readR::read_csv, CURL is somehow involved; I follow CURL is not a supported package for shinyLive. 
Looking up the, [supported shinyLive Packages,](https://repo.r-wasm.org/) readR appears to be fully supported and CURL is not listed as a dependent package. However, this [shinyLive Reproducible example](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IIgMQB1IowDWnAAT0onOPMbjGcKABMMBTgDd2QsN1KlUnRAHprzAO4YA5rVLcArvXcrGxMhVI9IhhrAEd3PmJ3MlYCbk4YCGsABU86AgBaABEoUigMgGUid184TmsYKD5rAFkAOQBSACYABgKAYQAJAoBBduaW5oA2Aa6AIQGsOBcScvbgmGjXVgHOrWo3AbGiFm0B5QGiADMBgEYAfVOAdnPWpoAWPUMTYQgxLKIyiAByUnl7aQyESaHSMRCIEHac76IwmMwWKy2BzOVweLw+PzkMhBELhSLFGJxBJJVL0dLZXL5IolAhlCpVJL1AYdbp9AbDUadCatKYzCBzBZLUgrVprKAbbhbHaMPatA6tY5nS43O6PGEvEQiCLyAA8GXkR2oEW0ySgTjgxgg8nknDo2jgjAAkhBUO5SMZICZcPITHUvfIYHx5ABeeSnb2VAAeIfkAFYWt6AMwtAS4ETWgwOpSkWgwAAqcEjpAA8m7Xe7ihY3Y7tDGTKQixqIK8RD5M4xdfqjtECDmSOw+OXvZXywJ5CB0-IR26ACQNv56tQUe2MAtF9gTq3W+SoZTkFoeq20BT+wez5uTgC+r0vmv5vH4PXQ7G1oYi3rbDpjn8YrzAl4AXSAA) shows what I am experiencing. This shinyLive application doesn't utilize the data but is here to show the application will not run if readr::read_csv is used. 

The base r function read.csv works great but where I am confused is CURL's involvement when using readR::read_csv since it doesn't seem readR utilizes CURL.

**Comment by quincountychsmn** [comment]
Thank you, George.

I'm sorry I missed the previous issue. I would not have created this extra issue if I saw it. Thank you for providing the link to it.

**Comment by georgestagg** [comment]
> I'm sorry I missed the previous issue. I would not have created this extra issue if I saw it.

No worries! Hope it helps.
