### ISSUE TITLE
Upgrade default shinylive assets version to shinylive >= 0.4.1

### ISSUE THREAD

**Issue by willgearty** [posit-dev/r-shinylive#93]
Is there any plan to upgrade the shinylive assets any time soon? It looks like shinylive 0.3.0 would be particularly useful since it further speeds up package loading. (although, it also looks like webR was just upgraded to version 0.4.0, so maybe it would be best to wait until shinylive picks up those changes?)

**Comment by gadenbuie** [comment]
We will upgrade to shinylive 0.4.1 or later in the next release, which we are working towards now.

**Comment by gadenbuie** [comment]
In the mean time, you can use the development version of `shinylive`, which added support for choosing the shinylive assets version at export or via an environment variable (see #91 for details).

```r
pak::pak("posit-dev/r-shinylive")

shinylive::export("app.R", assets_version = "0.4.1")
```

**Comment by willgearty** [comment]
Oh, that's fantastic, thanks!

**Comment by gadenbuie** [comment]
When this issue is closed, we should also close

* #63
* #27
