### ISSUE TITLE
Release shinylive 0.2.0

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/r-shinylive#94]
Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_shinylive.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `revdepcheck::cloud_check()`
* [x] Update `cran-comments.md`
* [x] `git push`
* [ ] Draft blog post
* [ ] Slack link to draft blog in #open-source-comms

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [ ] Finish & publish blog post
* [ ] Add link to blog post in pkgdown news menu
* [x] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version(push = TRUE)`
* [ ] Tweet
* [x] Update `actions-v1` tag

**Comment by schloerke** [comment]
On CRAN. 

Contemplating blog post.

**Comment by schloerke** [comment]
Past it's time. Closing

**Comment by georgestagg** [comment]
> Finish & publish blog post

https://www.tidyverse.org/blog/2024/10/shinylive-0-8-0/ is published now in any case, which contains essentially the same info.
